# Generated by Django 3.2.3 on 2021-05-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password2',
            new_name='password',
        ),
    ]
