# Generated by Django 3.2.3 on 2021-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures')),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
