# Generated by Django 3.2.3 on 2021-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0002_create_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_article',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
