# Generated by Django 3.2.3 on 2021-05-22 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0003_alter_create_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_article',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
